// docs/docs/.vuepress/components/VideoPlayer.vue
<style lang="stylus">
iframe {
  margin: auto;
}

.video {
  aspect-ratio: 16 / 9;
  width: 100%;
}
</style>

<template>
  <iframe
    class="video"
    :src="embedUrl"
    :title="title"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
  ></iframe>
</template>

<script>
export default {
  name: "VideoPlayer",
  props: {
    url: String,
    title: String,
    startAt: String,
  },
  computed: {
    embedUrl() {
      return `${this.url}${this.startAt ? `?start=${this.startAt}` : ""}`;
    },
  },
};
</script>

// docs-v2/components/VideoPlayer.tsx
import React from 'react';

const VideoPlayer = ({ src, title, startAt }) => {
  const embedUrl = `${src}${startAt ? `?start=${startAt}` : ""}`;

  return (
    <iframe
      className="mt-8 mx-auto aspect-video w-full"
      src={embedUrl}
      title={title}
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowFullScreen
    ></iframe>
  );
};

export default VideoPlayer;
